<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:24px;">Kebijakan Privasi</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Aplikasi Sentral Absensi ini juga hanya ditujukan untuk karyawan Sentral Sistem dan Karyawan Perusahaan Relasi dari Sentral Sistem.</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Sentral Sistem membangun aplikasi Sentral Absensi sebagai aplikasi Gratis. LAYANAN ini disediakan oleh Sentral Sistem tanpa biaya dan dimaksudkan untuk digunakan apa adanya.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Halaman ini digunakan untuk memberi tahu pengunjung mengenai kebijakan kami dengan pengumpulan, penggunaan, dan pengungkapan Informasi Pribadi jika ada yang memutuskan untuk menggunakan Layanan kami.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Jika Anda memilih untuk menggunakan Layanan kami, maka Anda menyetujui pengumpulan dan penggunaan informasi terkait dengan kebijakan ini. Informasi Pribadi yang kami kumpulkan digunakan untuk menyediakan dan meningkatkan Layanan. Kami tidak akan menggunakan atau membagikan informasi Anda kepada siapa pun kecuali sebagaimana dijelaskan dalam Kebijakan Privasi ini.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Jika memilih Layanan Aplikasi ini yaitu Sentral Sistem Absensi Anda juga setuju memberikan akses ke aplikasi untuk akses data lampiran yang dibutuhkan oleh system Absen. Lampiran bisa berupa evidence dari pengajuan cuti yang berupa file PDF ataupun alasan untuk ketidakhadiran. Lampiran juga bisa berupa foto (image) posisi absen.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Istilah yang digunakan dalam Kebijakan Privasi ini memiliki arti yang sama seperti dalam Syarat dan Ketentuan kami, yang dapat diakses di Sentral Absensi kecuali ditentukan lain dalam Kebijakan Privasi ini.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Pengumpulan dan Penggunaan Informasi</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Untuk pengalaman yang lebih baik, saat menggunakan Layanan kami, kami mungkin meminta Anda untuk memberikan kami informasi pengenal pribadi tertentu. Informasi yang kami minta akan disimpan oleh kami dan digunakan sebagaimana dijelaskan dalam kebijakan privasi ini.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Aplikasi ini memang menggunakan layanan pihak ketiga yang dapat mengumpulkan informasi yang digunakan untuk mengidentifikasi Anda.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Tautan ke kebijakan privasi penyedia layanan pihak ketiga yang digunakan oleh aplikasi&nbsp;</span></p>
<p><span style="font-family:Symbol;font-size:10,0000pt;">&middot;&nbsp;</span><a href="https://www.google.com/policies/privacy/"><u><span style="font-family:'Times New Roman';color:rgb(0,0,255);font-size:12,0000pt;color:rgb(0,0,255);">Layanan Google Play</span></u></a></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Ini adalah aplikasi Absen Sentral sistem jadi informasi</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;">yang kami kumpulkan meliputi nama,no handphone, posisi longitude dan latitude saat absen dan waktu absen serta foto pada saat melakukan absen.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Pengumpulan Informasi Lokasi</span></strong></p>
<p><span style="font-family:'Times New Roman';font-size:16px;">Ini adalah aplikasi Absen Sentral sistem jadi informasi</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;">yang kami kumpulkan&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;">termasuk lokasi akurat,</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;posisi longitude dan latitude</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;pada saat absen. Data tersebut kami gunakan untuk validasi Human Resource Departement Sentral Sistem untuk memastikan apakah user sudah absen sesuai lokasi atau tidak. Dat tersebut tidak kami sebarkan kemanapun juga dan hanya untuk kepentingan absen sentral sistem</span></p>
<p><strong><span style="font-family:'Times New Roman';font-weight:bold;">&nbsp;</span></strong></p>
<p><strong><span style="font-family:'Times New Roman';font-weight:bold;">Bagaimana Kami Menggunakan Informasi Anda</span></strong></p>
<p><span style="font-family:'Times New Roman';font-size:16px;">Informasi yang kami kumpulkan digunakan untuk</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;keperluan perusahaan</span><span style="font-family:'Times New Roman';font-size:16px;">:</span></p>
<p><span style="font-family:Symbol;font-size:13px;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:Calibri;font-size:11,0000pt;">Data absen karyawan Sentral Sistem yang digunakan oleh bagian Human Resource di Sentral Sistem.</span></p>
<p><span style="font-family:Symbol;font-size:13px;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:Calibri;font-size:11,0000pt;">Memperbaiki, menyesuaikan, dan meningkatkan aplikasi kami.</span></p>
<p><span style="font-family:Symbol;font-size:13px;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:Calibri;font-size:11,0000pt;">Mengirimkan pembaruan dan komunikasi terkait layanan kami.</span></p>
<p><span style="font-family:Symbol;font-size:13px;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:Calibri;font-size:11,0000pt;">Menanggapi pertanyaan dan dukungan pengguna.</span></p>
<p><span style="font-family:Symbol;font-size:13px;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:Calibri;font-size:11,0000pt;">Mematuhi kewajiban hukum.</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Log Data</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Kami ingin memberi tahu Anda bahwa setiap kali Anda menggunakan Layanan kami, jika terjadi kesalahan pada aplikasi, kami mengumpulkan data dan informasi (melalui produk pihak ketiga) di ponsel Anda yang disebut Data Log. Data Log ini dapat mencakup informasi seperti alamat Protokol Internet (&quot;IP&quot;) perangkat Anda, nama perangkat, versi sistem operasi, konfigurasi aplikasi ketika menggunakan Layanan kami, waktu dan tanggal penggunaan Layanan oleh Anda, dan statistik lainnya.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Cookies</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Cookies adalah file dengan sejumlah kecil data yang biasanya digunakan sebagai pengidentifikasi unik anonim. Ini dikirim ke browser Anda dari situs web yang Anda kunjungi dan disimpan di memori internal perangkat Anda.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Layanan ini tidak menggunakan &quot;cookie&quot; ini secara eksplisit. Namun, aplikasi dapat menggunakan kode pihak ketiga dan perpustakaan yang menggunakan &quot;cookie&quot; untuk mengumpulkan informasi dan meningkatkan layanan mereka. Anda memiliki opsi untuk menerima atau menolak cookie ini dan tahu kapan cookie dikirim ke perangkat Anda. Jika Anda memilih untuk menolak cookie kami, Anda mungkin tidak dapat menggunakan sebagian dari Layanan ini.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Penyedia Jasa</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Kami dapat mempekerjakan perusahaan pihak ketiga dan individu karena alasan berikut:&nbsp;</span></p>
<p><span style="font-family:Symbol;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;font-size:12,0000pt;">Untuk memfasilitasi Layanan kami;</span></p>
<p><span style="font-family:Symbol;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;font-size:12,0000pt;">Untuk menyediakan Layanan atas nama kami;</span></p>
<p><span style="font-family:Symbol;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;font-size:12,0000pt;">Untuk melakukan layanan terkait Layanan; atau</span></p>
<p><span style="font-family:Symbol;font-size:10,0000pt;">&middot;&nbsp;</span><span style="font-family:'Times New Roman';font-size:16px;font-size:12,0000pt;">Untuk membantu kami dalam menganalisis bagaimana Layanan kami digunakan.</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Kami ingin memberi tahu pengguna Layanan ini bahwa pihak ketiga ini memiliki akses ke Informasi Pribadi Anda. Alasannya adalah untuk melakukan tugas yang diberikan kepadanya atas nama kami. Namun, mereka berkewajiban untuk tidak mengungkapkan atau menggunakan informasi untuk tujuan lain apa pun.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Keamanan</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Kami menghargai kepercayaan Anda dalam memberikan Informasi Pribadi Anda kepada kami, sehingga kami berupaya untuk menggunakan cara yang dapat diterima secara komersial untuk melindunginya. Tetapi ingat bahwa tidak ada metode transmisi melalui internet, atau metode penyimpanan elektronik yang 100% aman dan andal, dan kami tidak dapat menjamin keamanan absolutnya.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Kebijakan Penghapusan Data:</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;text-indent:12,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Penghapusan Data:</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;text-indent:12,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Data absen dari user yang sudah masuk, tidak akan dihapus. Sentral sistem menggunakan data tersebut hanya untuk catatan history dan tidak disebarluaskan. Data user karyawan yang sudah resign akan dinonaktifkan oleh Sentral Sistem.</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp; &nbsp; Keterbukaan dan Transparansi:</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp; &nbsp; Kami berkomitmen untuk menjaga transparansi dan keterbukaan dalam hal pengelolaan data pengguna. Jika Anda memiliki pertanyaan atau kekhawatiran tentang kebijakan penghapusan data kami, jangan ragu untuk menghubungi tim dukungan kami. Jika suatu hal khusus Anda ingin meminta agar data Anda sebagai user ingin dihapus, karena Anda sudah tidak bekerja di Sentral Sistem maka Anda bisa menghubungi kontak kami via email.<br></span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Tautan ke Situs Lain</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Layanan ini dapat berisi tautan ke situs lain. Jika Anda mengklik tautan pihak ketiga, Anda akan diarahkan ke situs itu. Perhatikan bahwa situs eksternal ini tidak dioperasikan oleh kami. Karena itu, kami sangat menyarankan Anda untuk meninjau Kebijakan Privasi situs web ini. Kami tidak memiliki kendali atas dan tidak bertanggung jawab atas konten, kebijakan privasi, atau praktik situs atau layanan pihak ketiga mana pun.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Privasi Anak-Anak</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Layanan ini tidak membahas siapa pun yang berusia di bawah 13 tahun. Kami tidak secara sadar mengumpulkan informasi yang dapat diidentifikasi secara pribadi dari anak-anak di bawah 13. Dalam kasus kami menemukan bahwa seorang anak di bawah 13 tahun telah memberi kami informasi pribadi, kami segera menghapusnya dari server kami. Jika Anda adalah orang tua atau wali dan Anda mengetahui bahwa anak Anda telah memberi kami informasi pribadi, silakan hubungi kami agar kami dapat melakukan tindakan yang diperlukan.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Perubahan pada Kebijakan Privasi Ini</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Kami dapat memperbarui Kebijakan Privasi kami dari waktu ke waktu. Dengan demikian, Anda disarankan untuk meninjau halaman ini secara berkala untuk setiap perubahan. Kami akan memberi tahu Anda tentang segala perubahan dengan memposting Kebijakan Privasi baru di halaman ini. Perubahan ini efektif segera setelah diposting di halaman ini.&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><strong><span style="font-family:'Times New Roman';font-weight:bold;font-size:16px;">Hubungi kami</span></strong></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">Jika Anda memiliki pertanyaan atau saran tentang Kebijakan Privasi kami, jangan ragu untuk menghubungi kami di&nbsp;</span><a href="mailto:sentral.cloud.sistem@gmail.com"><u><span style="font-family:'Times New Roman';color:rgb(0,0,255);text-decoration:underline;font-size:16px;">sentral.cloud.sistem@gmail.com</span></u></a></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:Calibri;">Address:</span><span style="font-family:Calibri;font-size:15px;">&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:Calibri;font-size:15px;"><br></span><span style="font-family:Calibri;font-size:15px;">MT. Haryono Square, Floor 3A No.2 Jl. MT. Haryono Kav.10 Jakarta Timur 13330, Indonesia</span></p>
<p style="margin-bottom:0,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&middot;</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp; Phone: 021 2906 7201-3&nbsp;</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">&middot;</span><span style="font-family:'Times New Roman';font-size:16px;">&nbsp; Fax: 021 2906 7204</span></p>
<p style="margin-top:5,0000pt;margin-bottom:5,0000pt;"><span style="font-family:'Times New Roman';font-size:16px;">www.sentralsistem.com</span></p>